home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.profil, name='profil'),
    path('gilang/', views.gilang, name='gilang'),
    path('about/', views.about, name='about'),
]

story_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def profil(request):
    return render(request, 'profil.html')

def gilang(request):
    return render(request, 'Gilang.html')

def about(request):
    return render(request, 'About.html')

home/templates/About.html
<!DOCTYPE html>
{% load static %}
<html>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<body style="background-color:lightblue">

<h2 class="text-center">Gilang Mahardhika <br>Pratama </h2>
<p class="text-center">Fotografer</p>
<ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'home:gilang' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'home:about' %}">About</a>
    </li>
  </ul>

<p style="margin: 80px">Halo, nama saya Gilang, saya adalah mahasiswa Universitas Indonesia jurusan sistem informasi fakultas ilmu komputer.
Saya senang bermain games dan menonton anime, saya juga memiliki hobi untuk fotografi,
hobi tersebut muncul karena keinginan dan impian saya untuk berkeliling dunia. Saya mulai mengenal fotografi saat saya berada di bangku SMA,
disana saya mengikuti ekskul fotografi dan dari ekskul tersebut saya mulai diajarkan fotografi dan dari situ saya mengembangkan hobi baru.
Saya sudah pernah mengikuti hunting foto yang diadakan ekskul, saya juga sudah pernah mengikuti kegiatan dan acara yang diadakan di SMA
dan saya sering menjadi panitia dokumentasi.</p>

<p style="margin: 80px">Social media:<br>Line: ken_ginga<br>WA: 087876367179<br>Instagram: <a href="https://www.instagram.com/shoutginga/?hl=en">shoutginga</a></p>

</body>
</html>

home/templates/Gilang.html
<!DOCTYPE html>
{% load static %}
<html>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
<body style="background-color:lightblue">

<h2 class="text-center">Gilang Mahardhika <br>Pratama </h2>
<p class="text-center">Fotografer</p>
<ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'home:gilang' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'home:about' %}">About</a>
    </li>
  </ul>
  
<style>
figure {
  padding: 4px;
  margin: 30px 120px;
}

figcaption {
  background-color: black;
  color: white;
  font-style: italic;
  padding: 5px;
  text-align: center;
}
</style>
<figure>
    <img src="{% static 'IMG_6993.jpg' %}" width=100%>
    <figcaption style="width: 100%">Sample photo</figcaption>
</figure>
<figure>
    <img src="{% static 'IMG_1098.JPG' %}" width=100%>
    <figcaption style="width: 100%">Sample photo</figcaption>
</figure>
<figure>
    <img src="{% static 'IMG_0458.JPG' %}" width=100%>
    <figcaption style="width: 100%">Sample photo</figcaption>
</figure>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

home/templates/profil.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<body style="background-color:lightblue">

<h2>Gilang Mahardhika Pratama</h2>
<img src="{% static 'IMG_2014.PNG' %}" width="250" height="250">
<p>1906303102</p>
<p>Maung</p>
<p>Sistem Informasi</p>
<p>Hobi: <br> Anime <br> Games <br> Fotografi</p>
<p>Halo, nama saya Gilang, saya adalah mahasiswa Universitas Indonesia jurusan sistem informasi fakultas ilmu komputer. <br>
Saya senang bermain games dan menonton anime, saya juga memiliki hobi untuk fotografi, <br>
hobi tersebut muncul karena keinginan dan impian saya untuk berkeliling dunia.</p>
<p>Media sosial: <br> Line: ken_ginga <br> Instagram: shoutginga <br> Website: <a href="{% url 'home:gilang' %}">Here</a></p>

</body>
</html>